### ISSUE TITLE
Support Intellij IDEA 2016.3 and newer

### ISSUE THREAD

**Issue by markiewb** [krrrr38/intellij-mockito-postfix-plugin#1]

**Comment by markiewb** [comment]
See PR #2

**Comment by krrrr38** [comment]
Now, you can use this plugin from latest Intellij IDEA. Thanks.
[![https://gyazo.com/0576a751d939c04bcb04c696561f6774](https://i.gyazo.com/0576a751d939c04bcb04c696561f6774.png)](https://gyazo.com/0576a751d939c04bcb04c696561f6774)
