### ISSUE TITLE
BDD Mockito

### ISSUE THREAD

**Issue by achimgrimm** [krrrr38/intellij-mockito-postfix-plugin#4]
Hi,
would it be possible to add support for BDD Mockito (https://www.baeldung.com/bdd-mockito) as well?

I am happy to help with the change, if you like.

**Comment by krrrr38** [comment]
@achimgrimm 
Thank you for your proposal issue.

Add BDDMockito support in #5.
Currently not supported yet `BDDMockito.when`, but you can use `Mockito.when`.

You can use this feature from intellij-mockito-postfix-plugin 0.0.8. It will available soon, after JetBrains approve my published one.

**Comment by krrrr38** [comment]
it's available now
![image](https://user-images.githubusercontent.com/915731/83083030-fd793c00-a0bf-11ea-8d0e-b47516434bc8.png)

**Comment by achimgrimm** [comment]
Cool. Thank you very much for the very fast change. :)
